# Generated by Django 5.0.14 on 2026-04-24 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_catalogitem_interactionrecord_tenantconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="owner",
            field=models.ForeignKey(
                help_text="Tenant owner for RBAC mapping",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
