# Generated by Django 5.0.6 on 2026-04-26 17:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenant_whisper_api_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "permissions": (
                    ("deactivate_plan", "Can deactivate SaaS plan"),
                    ("assign_plan", "Can assign SaaS plan to tenant"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "permissions": (
                    ("suspend_tenant", "Can suspend tenant"),
                    ("reactivate_tenant", "Can reactivate tenant"),
                    ("deploy_tenant", "Can deploy tenant infrastructure"),
                    ("rotate_tenant_secret", "Can rotate tenant secrets"),
                    ("view_tenant_usage", "Can view tenant usage"),
                )
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="a0_cpu_limit",
            field=models.CharField(default="2.0", max_length=16),
        ),
        migrations.AddField(
            model_name="plan",
            name="a0_cpu_reservation",
            field=models.CharField(default="1.0", max_length=16),
        ),
        migrations.AddField(
            model_name="plan",
            name="a0_image",
            field=models.CharField(
                default="agent0ai/agent-zero-tenant:latest", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="a0_memory_limit",
            field=models.CharField(default="3g", max_length=16),
        ),
        migrations.AddField(
            model_name="plan",
            name="a0_memory_reservation",
            field=models.CharField(default="1g", max_length=16),
        ),
        migrations.AddField(
            model_name="plan",
            name="allow_catalog_upload",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="allow_creator_override",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="allow_custom_domain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="allow_human_handoff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="allow_integrations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="allow_voice_messages",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_agent_contexts",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_catalog_items",
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_messages_per_day",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_messages_per_minute",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_storage_mb",
            field=models.IntegerField(default=1024),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_transcription_minutes",
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_users",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="vultr_plan",
            field=models.CharField(default="vc2-2c-4gb", max_length=64),
        ),
        migrations.AlterField(
            model_name="interactionrecord",
            name="payload",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="assigned_port",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Deployment"),
                    ("pending_payment", "Pending Payment"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("suspended", "Suspended"),
                    ("suspended_limit", "Suspended: Plan Limit"),
                    ("suspended_billing", "Suspended: Billing"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="vultr_instance_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vaultrecord",
            unique_together={("tenant", "vault_path")},
        ),
        migrations.CreateModel(
            name="ServiceCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key_prefix", models.CharField(db_index=True, max_length=12)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_credentials",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("external_customer_id", models.CharField(blank=True, max_length=128)),
                (
                    "external_subscription_id",
                    models.CharField(blank=True, max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.plan"
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("change_subscription_plan", "Can change tenant subscription plan"),
                ),
            },
        ),
        migrations.CreateModel(
            name="TenantPlanHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="new_tenant_assignments",
                        to="tenants.plan",
                    ),
                ),
                (
                    "old_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_tenant_assignments",
                        to="tenants.plan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_history",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("service", "Service"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("target_type", models.CharField(blank=True, max_length=80)),
                ("target_id", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "actor_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.servicecredential",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_security_audit", "Can view security audit events"),
                ),
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="tenants_aud_action_827702_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="tenants_aud_tenant__955c9c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("conversations_used", models.IntegerField(default=0)),
                ("messages_used", models.IntegerField(default=0)),
                ("transcription_seconds_used", models.IntegerField(default=0)),
                ("catalog_items_used", models.IntegerField(default=0)),
                ("storage_bytes_used", models.BigIntegerField(default=0)),
                ("last_reported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "period_start"],
                        name="tenants_ten_tenant__5f150f_idx",
                    )
                ],
                "unique_together": {("tenant", "period_start")},
            },
        ),
    ]
