# Generated by Django 5.0.6 on 2026-05-01 17:56

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_remove_tenant_whisper_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='creator_session_pin',
        ),
        migrations.AddField(
            model_name='tenant',
            name='creator_session_pin_hash',
            field=models.CharField(blank=True, help_text='PBKDF2 hash of temporary session PIN for God Mode challenge', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='value',
            field=common.fields.EncryptedTextField(help_text='Encrypted at rest. Stores sensitive config like MASTER_CREATOR_PASSWORD.'),
        ),
        migrations.AlterField(
            model_name='interactionrecord',
            name='payload',
            field=common.fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='value',
            field=common.fields.EncryptedTextField(),
        ),
    ]
