# Generated by Django 5.0.6 on 2026-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_remove_tenant_creator_session_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='deployment_backend',
            field=models.CharField(choices=[('docker', 'Docker (Local)'), ('vultr', 'Vultr (Cloud)')], default='vultr', help_text="Which backend deployed this tenant's pod", max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='docker_container_id',
            field=models.CharField(blank=True, help_text='Docker container ID for locally deployed tenants', max_length=64, null=True),
        ),
    ]
