# Generated by Django 5.0.14 on 2026-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_deployment_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='a0_image',
            field=models.CharField(default='avenderpod:latest', max_length=255),
        ),
    ]
