# Generated by Codex on 2026-05-09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_rename_a0_image_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "permissions": (
                    ("suspend_tenant", "Can suspend tenant"),
                    ("reactivate_tenant", "Can reactivate tenant"),
                    ("deploy_tenant", "Can deploy tenant infrastructure"),
                    ("rotate_tenant_secret", "Can rotate tenant secrets"),
                    ("view_tenant_usage", "Can view tenant usage"),
                    ("initiate_creator_override", "Can initiate creator override"),
                    ("verify_creator_override", "Can verify creator override challenge"),
                    ("impersonate_tenant", "Can impersonate tenant"),
                    ("view_creator_challenge", "Can view creator override challenges"),
                )
            },
        ),
        migrations.CreateModel(
            name="PodDeployment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pod_name", models.CharField(db_index=True, max_length=128)),
                ("is_development", models.BooleanField(default=False)),
                (
                    "deployment_backend",
                    models.CharField(
                        choices=[("docker", "Docker (Local)"), ("vultr", "Vultr (Cloud)")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("provider_resource_id", models.CharField(blank=True, default="", max_length=128)),
                ("avender_container_id", models.CharField(blank=True, default="", max_length=128)),
                ("tenant_vault_container_id", models.CharField(blank=True, default="", max_length=128)),
                ("image_tag", models.CharField(blank=True, default="", max_length=255)),
                ("assigned_port", models.IntegerField(blank=True, db_index=True, null=True)),
                ("public_url", models.URLField(blank=True, default="")),
                ("private_url", models.URLField(blank=True, default="")),
                ("effective_plan_snapshot", models.JSONField(blank=True, default=dict)),
                ("effective_rate_limits", models.JSONField(blank=True, default=dict)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("stopped", "Stopped"),
                            ("restarting", "Restarting"),
                            ("suspended", "Suspended"),
                            ("deleting", "Deleting"),
                            ("deleted", "Deleted"),
                            ("failed", "Failed"),
                            ("degraded", "Degraded"),
                            ("drifted", "Drifted"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="provisioning",
                        max_length=24,
                    ),
                ),
                (
                    "provider_health_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("healthy", "Healthy"),
                            ("unhealthy", "Unhealthy"),
                            ("unreachable", "Unreachable"),
                            ("missing", "Missing"),
                            ("not_configured", "Not Configured"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "tenant_vault_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("healthy", "Healthy"),
                            ("unhealthy", "Unhealthy"),
                            ("unreachable", "Unreachable"),
                            ("missing", "Missing"),
                            ("not_configured", "Not Configured"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("last_lifecycle_action", models.CharField(blank=True, default="", max_length=32)),
                ("last_health_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_lifecycle_action_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pod_deployments", to="tenants.tenant"),
                ),
            ],
            options={
                "permissions": (
                    ("deploy_poddeployment", "Can deploy pod deployment"),
                    ("stop_poddeployment", "Can stop pod deployment"),
                    ("restart_poddeployment", "Can restart pod deployment"),
                    ("suspend_poddeployment", "Can suspend pod deployment"),
                    ("reactivate_poddeployment", "Can reactivate pod deployment"),
                    ("reconcile_poddeployment", "Can reconcile pod deployments"),
                    ("view_pod_logs", "Can view pod logs"),
                    ("view_pod_health", "Can view pod health"),
                )
            },
        ),
        migrations.AddIndex(
            model_name="poddeployment",
            index=models.Index(fields=["tenant", "lifecycle_state"], name="tenants_pod_tenant__f25d43_idx"),
        ),
        migrations.AddIndex(
            model_name="poddeployment",
            index=models.Index(fields=["deployment_backend", "provider_resource_id"], name="tenants_pod_deploym_9b192b_idx"),
        ),
    ]
